// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjfyef3CoG68XecHI7RtDbV4JgU5buu8Y',
    appId: '1:807638818748:web:d93eae714a1eb9cf5315b9',
    messagingSenderId: '807638818748',
    projectId: 'panda-chat-e9ce8',
    authDomain: 'panda-chat-e9ce8.firebaseapp.com',
    storageBucket: 'panda-chat-e9ce8.appspot.com',
    measurementId: 'G-H3W0WX5KRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRecHcOE_8Z3Uzu8IW9uKBi6Mi-XHUDKI',
    appId: '1:807638818748:android:310bd09b42aed9135315b9',
    messagingSenderId: '807638818748',
    projectId: 'panda-chat-e9ce8',
    storageBucket: 'panda-chat-e9ce8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArrgxFJ3em7HhJuF8VDXtEiwoMJzQj7wg',
    appId: '1:807638818748:ios:6355e901c8e66cfa5315b9',
    messagingSenderId: '807638818748',
    projectId: 'panda-chat-e9ce8',
    storageBucket: 'panda-chat-e9ce8.appspot.com',
    iosClientId: '807638818748-dh3lpqrpvt73892jm88me4fgsa6jhi0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArrgxFJ3em7HhJuF8VDXtEiwoMJzQj7wg',
    appId: '1:807638818748:ios:6355e901c8e66cfa5315b9',
    messagingSenderId: '807638818748',
    projectId: 'panda-chat-e9ce8',
    storageBucket: 'panda-chat-e9ce8.appspot.com',
    iosClientId: '807638818748-dh3lpqrpvt73892jm88me4fgsa6jhi0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
